### ISSUE TITLE
Return URLs always append ? without checking if it's correct

### ISSUE THREAD

**Issue by rootpd** [tomaj/payment-simulator#1]
If the client's return URL contains GET parameter, appending gateway parameters with `?` character breaks the flow.

For example if my return URL is:  
`http://crm.press/return?foo=bar`

The gateway will generate following (which breaks the expected response):
`http://crm.press/return?foo=bar?VS=12345&...`

Implementations should always check whether to use `?` or `&` as a first character when appending query parameters.

**Comment by tomaj** [comment]
It is fixed and live on https://platby.tomaj.sk/
